import pyautogui
from PIL import Image, ImageDraw
import cv2

class Screen(object):
    def __init__(self):
        self.mainScreen = ...
        self.mainScreenScale = ...
        self.subScreen = ...
        self.subScreenScale = ...

    def getScreenshot(self, mainScreen=True) -> Image:
        ...